/**
 * All command IDs used in the keymap registry.
 * This is the single source of truth for command identifiers.
 */
export const ALL_COMMAND_IDS = [
  "file.save",
  "file.saveAs",
  "file.open",
  "file.print",
  "file.newWindow",
  "file.newTab",
  "file.closeTab",
  "edit.undo",
  "edit.redo",
  "edit.pasteAsPlaintext",
  "edit.selectAll",
  "view.zoomIn",
  "view.zoomOut",
  "view.resetZoom",
  "view.compactMode",
  "view.toggleWritingMode",
  "view.splitRight",
  "view.splitDown",
  "nav.nextTab",
  "nav.prevTab",
  "nav.tab1",
  "nav.tab2",
  "nav.tab3",
  "nav.tab4",
  "nav.tab5",
  "nav.tab6",
  "nav.tab7",
  "nav.tab8",
  "nav.tab9",
  "nav.settings",
  "nav.search",
  "panel.explorer",
  "panel.files",
  "panel.search",
  "panel.dictionary",
  "panel.wordfreq",
  "terminal.new",
  "inspector.corrections",
  "inspector.stats",
  "inspector.history",
  // "panel.outline", // TODO: Outline feature — planned for v1.3.0
  "format.ruby",
  "format.tcy",
] as const;

export type CommandId = (typeof ALL_COMMAND_IDS)[number];
