/**
 * Issue #1449 — export-pipeline equivalence proof.
 *
 * `__fixtures__/mdi-pipeline-baseline.json` was generated by running the
 * PRE-refactor export pipeline (dev @ 750ebaf, before the MdiDocument
 * consolidation) on a representative MDI document covering every MDI 1.0
 * construct: group ruby, split ruby, tate-chu-yoko, no-break, kern, [[br]],
 * heading, horizontal rule (scene break), multiple [[blank]] blank
 * paragraphs, and escaped MDI characters.
 * (傍点 / 改ページ are not MDI 1.0 constructs and have no marker syntax.)
 *
 * These tests assert the post-refactor pipeline produces byte-identical
 * output (for docx: an identical word/document.xml) so the consolidation is
 * provably behavior-preserving.
 */

import { describe, it, expect } from "vitest";
import { unzipSync, strFromU8 } from "fflate";
import { mdiToHtml } from "@/lib/export/mdi-to-html";
import { mdiToPlainText, mdiToRubyText } from "@/lib/export/txt-exporter";
import { generateDocxBlob } from "@/lib/export/docx-exporter";
import { MdiDocument } from "@/packages/milkdown-plugin-japanese-novel/mdi-document";
import baseline from "./__fixtures__/mdi-pipeline-baseline.json";

describe("MDI export pipeline equivalence (#1449, baseline = pre-refactor output)", () => {
  it("txt (plain) — byte-identical via exporter entry", () => {
    expect(mdiToPlainText(baseline.doc)).toBe(baseline.plain);
  });

  it("txt (plain) — byte-identical via MdiDocument.toExportText", () => {
    expect(MdiDocument.fromRawText(baseline.doc).toExportText("txt")).toBe(baseline.plain);
  });

  it("txt (ruby) — byte-identical via exporter entry", () => {
    expect(mdiToRubyText(baseline.doc)).toBe(baseline.ruby);
  });

  it("txt (ruby) — byte-identical via MdiDocument.toExportText", () => {
    expect(MdiDocument.fromRawText(baseline.doc).toExportText("txt-ruby")).toBe(baseline.ruby);
  });

  it("html — byte-identical body output", () => {
    expect(mdiToHtml(baseline.doc, { bodyOnly: true })).toBe(baseline.html);
  });

  it("docx — identical word/document.xml", async () => {
    const blob = await generateDocxBlob(baseline.doc, {
      metadata: { title: "T", language: "ja" },
    });
    const arrayBuffer = await blob.arrayBuffer();
    const unzipped = unzipSync(new Uint8Array(arrayBuffer));
    const documentXml = strFromU8(unzipped["word/document.xml"]!);
    expect(documentXml).toBe(baseline.docxXml);
  });

  it("no [[blank]] literal leaks into any export output", () => {
    expect(baseline.plain).not.toContain("[[blank]]");
    expect(baseline.ruby).not.toContain("[[blank]]");
    expect(baseline.html).not.toContain("[[blank]]");
    expect(baseline.docxXml).not.toContain("[[blank]]");
  });
});
